language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: EmbeddingPolicy
- name: FormPolicy
- name: TwoStageFallbackPolicy
